# Form implementation generated from reading ui file 'E:\Final_KTLT\USER_INTERFACE\Login\MainWindowSignup.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Signup(object):
    def setupUi(self, Signup):
        Signup.setObjectName("Signup")
        Signup.resize(950, 711)
        Signup.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.centralwidget = QtWidgets.QWidget(parent=Signup)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 949, 661))
        self.label_2.setStyleSheet("background-color: rgb(242, 248, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(24, 24, 901, 73))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 80))
        self.label_3.setStyleSheet("font: 75 22pt \"CocogooseProTrial Bold\";\n"
"color: rgb(5, 129, 253);\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius: 20px; ")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(24, 108, 901, 469))
        self.groupBox.setStyleSheet("padding: 5px;\n"
"border-radius: 10px;\n"
"color: rgb(155, 159, 162);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 25 10pt \"Montserrat Light\";")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(24, 36, 397, 397))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEditUsername_2 = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.lineEditUsername_2.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lineEditUsername_2.setFont(font)
        self.lineEditUsername_2.setToolTipDuration(-1)
        self.lineEditUsername_2.setStyleSheet("background-color: rgb(242, 248, 255);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";\n"
"padding: 10px;")
        self.lineEditUsername_2.setText("")
        self.lineEditUsername_2.setFrame(False)
        self.lineEditUsername_2.setObjectName("lineEditUsername_2")
        self.verticalLayout_2.addWidget(self.lineEditUsername_2)
        self.lineEditPassword_2 = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.lineEditPassword_2.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lineEditPassword_2.setFont(font)
        self.lineEditPassword_2.setToolTipDuration(-1)
        self.lineEditPassword_2.setStyleSheet("background-color: rgb(242, 248, 255);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";\n"
"padding: 10px;")
        self.lineEditPassword_2.setText("")
        self.lineEditPassword_2.setFrame(False)
        self.lineEditPassword_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEditPassword_2.setObjectName("lineEditPassword_2")
        self.verticalLayout_2.addWidget(self.lineEditPassword_2)
        self.lineEditPassword_3 = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.lineEditPassword_3.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lineEditPassword_3.setFont(font)
        self.lineEditPassword_3.setToolTipDuration(-1)
        self.lineEditPassword_3.setStyleSheet("background-color: rgb(242, 248, 255);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";\n"
"padding: 10px;")
        self.lineEditPassword_3.setText("")
        self.lineEditPassword_3.setFrame(False)
        self.lineEditPassword_3.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEditPassword_3.setObjectName("lineEditPassword_3")
        self.verticalLayout_2.addWidget(self.lineEditPassword_3)
        self.lineEditPassword_4 = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.lineEditPassword_4.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lineEditPassword_4.setFont(font)
        self.lineEditPassword_4.setToolTipDuration(-1)
        self.lineEditPassword_4.setStyleSheet("background-color: rgb(242, 248, 255);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";\n"
"padding: 10px;")
        self.lineEditPassword_4.setText("")
        self.lineEditPassword_4.setFrame(False)
        self.lineEditPassword_4.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEditPassword_4.setObjectName("lineEditPassword_4")
        self.verticalLayout_2.addWidget(self.lineEditPassword_4)
        self.lineEditPassword_5 = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.lineEditPassword_5.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lineEditPassword_5.setFont(font)
        self.lineEditPassword_5.setToolTipDuration(-1)
        self.lineEditPassword_5.setStyleSheet("background-color: rgb(242, 248, 255);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";\n"
"padding: 10px;")
        self.lineEditPassword_5.setText("")
        self.lineEditPassword_5.setFrame(False)
        self.lineEditPassword_5.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEditPassword_5.setObjectName("lineEditPassword_5")
        self.verticalLayout_2.addWidget(self.lineEditPassword_5)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=self.groupBox)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(480, 36, 397, 241))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEditUsername_3 = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_3)
        self.lineEditUsername_3.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lineEditUsername_3.setFont(font)
        self.lineEditUsername_3.setToolTipDuration(-1)
        self.lineEditUsername_3.setStyleSheet("background-color: rgb(243, 243, 243);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";\n"
"padding: 10px;")
        self.lineEditUsername_3.setText("")
        self.lineEditUsername_3.setFrame(False)
        self.lineEditUsername_3.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEditUsername_3.setObjectName("lineEditUsername_3")
        self.verticalLayout_3.addWidget(self.lineEditUsername_3)
        self.lineEditPassword_6 = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_3)
        self.lineEditPassword_6.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lineEditPassword_6.setFont(font)
        self.lineEditPassword_6.setToolTipDuration(-1)
        self.lineEditPassword_6.setStyleSheet("background-color: rgb(243, 243, 243);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";\n"
"padding: 10px;")
        self.lineEditPassword_6.setText("")
        self.lineEditPassword_6.setFrame(False)
        self.lineEditPassword_6.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword_6.setObjectName("lineEditPassword_6")
        self.verticalLayout_3.addWidget(self.lineEditPassword_6)
        self.lineEditPassword_7 = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_3)
        self.lineEditPassword_7.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lineEditPassword_7.setFont(font)
        self.lineEditPassword_7.setToolTipDuration(-1)
        self.lineEditPassword_7.setStyleSheet("background-color: rgb(243, 243, 243);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";\n"
"padding: 10px;")
        self.lineEditPassword_7.setText("")
        self.lineEditPassword_7.setFrame(False)
        self.lineEditPassword_7.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword_7.setObjectName("lineEditPassword_7")
        self.verticalLayout_3.addWidget(self.lineEditPassword_7)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(480, 288, 397, 145))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonLogin_2 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButtonLogin_2.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButtonLogin_2.setFont(font)
        self.pushButtonLogin_2.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButtonLogin_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButtonLogin_2.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #35B6E8; /* Màu nền mặc định */\n"
"    font: 57 12pt \"Montserrat Medium\";color: rgb(255, 255, 255);\n"
"    border-radius: 10px; \n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A3E3FC; /* Màu khi di chuột */  \n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #35B6E8; /* Màu khi nhấn */\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 5px solid #A3E3FC; /* Viền khi nút được focus */ \n"
"}\n"
"\n"
"")
        self.pushButtonLogin_2.setObjectName("pushButtonLogin_2")
        self.verticalLayout.addWidget(self.pushButtonLogin_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(11)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonLogin = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButtonLogin.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButtonLogin.setFont(font)
        self.pushButtonLogin.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButtonLogin.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButtonLogin.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #0581F9; /* Màu nền mặc định */\n"
"    font: 57 12pt \"Montserrat Medium\";color: rgb(255, 255, 255);\n"
"    border-radius: 10px; \n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #87C4FF; /* Màu khi di chuột */  \n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0581F9; /* Màu khi nhấn */\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 5px solid #87C4FF; /* Viền khi nút được focus */ \n"
"}\n"
"")
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.horizontalLayout_2.addWidget(self.pushButtonLogin)
        self.pushButtonLogin_3 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButtonLogin_3.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButtonLogin_3.setFont(font)
        self.pushButtonLogin_3.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButtonLogin_3.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButtonLogin_3.setStyleSheet("QPushButton {\n"
"    background-color: #FF2090; /* Màu nền mặc định */\n"
"    font: 57 12pt \"Montserrat Medium\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px; \n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFA2D1; /* Màu khi di chuột */  \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FF2090; /* Màu khi nhấn */\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 5px solid #FFA2D1; /* Viền khi nút được focus */ \n"
"}\n"
"")
        self.pushButtonLogin_3.setObjectName("pushButtonLogin_3")
        self.horizontalLayout_2.addWidget(self.pushButtonLogin_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(444, 96, 2, 250))
        self.label.setMaximumSize(QtCore.QSize(2, 250))
        self.label.setStyleSheet("background-color: rgb(155, 159, 162);")
        self.label.setObjectName("label")
        Signup.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Signup)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 26))
        self.menubar.setObjectName("menubar")
        Signup.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Signup)
        self.statusbar.setObjectName("statusbar")
        Signup.setStatusBar(self.statusbar)

        self.retranslateUi(Signup)
        QtCore.QMetaObject.connectSlotsByName(Signup)

    def retranslateUi(self, Signup):
        _translate = QtCore.QCoreApplication.translate
        Signup.setWindowTitle(_translate("Signup", "Sign up"))
        self.label_3.setText(_translate("Signup", "Create Account "))
        self.groupBox.setTitle(_translate("Signup", "Staff Information "))
        self.lineEditUsername_2.setPlaceholderText(_translate("Signup", "Staff ID"))
        self.lineEditPassword_2.setPlaceholderText(_translate("Signup", "Name"))
        self.lineEditPassword_3.setPlaceholderText(_translate("Signup", "Position"))
        self.lineEditPassword_4.setPlaceholderText(_translate("Signup", "Phone"))
        self.lineEditPassword_5.setPlaceholderText(_translate("Signup", "Email"))
        self.lineEditUsername_3.setPlaceholderText(_translate("Signup", "Username"))
        self.lineEditPassword_6.setPlaceholderText(_translate("Signup", "Password"))
        self.lineEditPassword_7.setPlaceholderText(_translate("Signup", "Password again(*)"))
        self.pushButtonLogin_2.setText(_translate("Signup", "Create"))
        self.pushButtonLogin.setText(_translate("Signup", "Clear"))
        self.pushButtonLogin_3.setText(_translate("Signup", "Cancel"))
        self.label.setText(_translate("Signup", "TextLabel"))
