# Form implementation generated from reading ui file 'C:\Users\Nicolee\Coding\Final_KTLT\USER_INTERFACE\Import\MainWindowImport.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindowImport(object):
    def setupUi(self, MainWindowImport):
        MainWindowImport.setObjectName("MainWindowImport")
        MainWindowImport.resize(1389, 855)
        MainWindowImport.setMaximumSize(QtCore.QSize(1920, 1080))
        MainWindowImport.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        MainWindowImport.setAutoFillBackground(False)
        MainWindowImport.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        MainWindowImport.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindowImport)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(24, 24, 229, 793))
        self.label.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(36, 180, 205, 517))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonProduct = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButtonProduct.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButtonProduct.setToolTipDuration(-1)
        self.pushButtonProduct.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButtonProduct.setAutoFillBackground(False)
        self.pushButtonProduct.setStyleSheet("font: 63 12pt \"Montserrat SemiBold\";\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid #9b9fa2;\n"
"color: rgb(155, 159, 162);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Nicolee\\Coding\\Final_KTLT\\USER_INTERFACE\\Import\\../../RESOURCE/ICON/album2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonProduct.setIcon(icon)
        self.pushButtonProduct.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonProduct.setObjectName("pushButtonProduct")
        self.verticalLayout.addWidget(self.pushButtonProduct)
        self.pushButtonAdmin = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButtonAdmin.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButtonAdmin.setToolTipDuration(-1)
        self.pushButtonAdmin.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButtonAdmin.setAutoFillBackground(False)
        self.pushButtonAdmin.setStyleSheet("font: 63 12pt \"Montserrat SemiBold\";\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid #9b9fa2;\n"
"color: rgb(155, 159, 162);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\Nicolee\\Coding\\Final_KTLT\\USER_INTERFACE\\Import\\../../RESOURCE/ICON/adm2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonAdmin.setIcon(icon1)
        self.pushButtonAdmin.setIconSize(QtCore.QSize(35, 35))
        self.pushButtonAdmin.setObjectName("pushButtonAdmin")
        self.verticalLayout.addWidget(self.pushButtonAdmin)
        self.pushButtonVendor = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButtonVendor.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButtonVendor.setToolTipDuration(-1)
        self.pushButtonVendor.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButtonVendor.setAutoFillBackground(False)
        self.pushButtonVendor.setStyleSheet("font: 63 12pt \"Montserrat SemiBold\";\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid #9b9fa2;\n"
"color: rgb(155, 159, 162);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\Nicolee\\Coding\\Final_KTLT\\USER_INTERFACE\\Import\\../../RESOURCE/ICON/vendor1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonVendor.setIcon(icon2)
        self.pushButtonVendor.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonVendor.setObjectName("pushButtonVendor")
        self.verticalLayout.addWidget(self.pushButtonVendor)
        self.pushButtonImport = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButtonImport.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButtonImport.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.pushButtonImport.setToolTipDuration(0)
        self.pushButtonImport.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButtonImport.setAutoFillBackground(False)
        self.pushButtonImport.setStyleSheet("font: 63 12pt \"Montserrat SemiBold\";\n"
"color: rgb(14, 23, 67);\n"
"background-color: rgb(242, 248, 255)")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:\\Users\\Nicolee\\Coding\\Final_KTLT\\USER_INTERFACE\\Import\\../../RESOURCE/ICON/import2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonImport.setIcon(icon3)
        self.pushButtonImport.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonImport.setObjectName("pushButtonImport")
        self.verticalLayout.addWidget(self.pushButtonImport)
        self.pushButtonReceipt = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButtonReceipt.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButtonReceipt.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.pushButtonReceipt.setToolTipDuration(0)
        self.pushButtonReceipt.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButtonReceipt.setAutoFillBackground(False)
        self.pushButtonReceipt.setStyleSheet("font: 63 12pt \"Montserrat SemiBold\";\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid #9b9fa2;\n"
"color: rgb(155, 159, 162);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:\\Users\\Nicolee\\Coding\\Final_KTLT\\USER_INTERFACE\\Import\\../../RESOURCE/ICON/doc.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonReceipt.setIcon(icon4)
        self.pushButtonReceipt.setIconSize(QtCore.QSize(35, 35))
        self.pushButtonReceipt.setObjectName("pushButtonReceipt")
        self.verticalLayout.addWidget(self.pushButtonReceipt)
        self.pushButtonExport = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButtonExport.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButtonExport.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.pushButtonExport.setToolTipDuration(0)
        self.pushButtonExport.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButtonExport.setAutoFillBackground(False)
        self.pushButtonExport.setStyleSheet("font: 63 12pt \"Montserrat SemiBold\";\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid #9b9fa2;\n"
"color: rgb(155, 159, 162);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:\\Users\\Nicolee\\Coding\\Final_KTLT\\USER_INTERFACE\\Import\\../../RESOURCE/ICON/export.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonExport.setIcon(icon5)
        self.pushButtonExport.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonExport.setObjectName("pushButtonExport")
        self.verticalLayout.addWidget(self.pushButtonExport)
        self.pushButtonInvoice = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButtonInvoice.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButtonInvoice.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.pushButtonInvoice.setToolTipDuration(0)
        self.pushButtonInvoice.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButtonInvoice.setAutoFillBackground(False)
        self.pushButtonInvoice.setStyleSheet("font: 63 12pt \"Montserrat SemiBold\";\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid #9b9fa2;\n"
"color: rgb(155, 159, 162);")
        self.pushButtonInvoice.setIcon(icon4)
        self.pushButtonInvoice.setIconSize(QtCore.QSize(35, 35))
        self.pushButtonInvoice.setObjectName("pushButtonInvoice")
        self.verticalLayout.addWidget(self.pushButtonInvoice)
        self.pushButtonInventory = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButtonInventory.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButtonInventory.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.pushButtonInventory.setToolTipDuration(0)
        self.pushButtonInventory.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButtonInventory.setAutoFillBackground(False)
        self.pushButtonInventory.setStyleSheet("font: 63 12pt \"Montserrat SemiBold\";\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid #9b9fa2;\n"
"color: rgb(155, 159, 162);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:\\Users\\Nicolee\\Coding\\Final_KTLT\\USER_INTERFACE\\Import\\../../RESOURCE/ICON/inventory.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonInventory.setIcon(icon6)
        self.pushButtonInventory.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonInventory.setObjectName("pushButtonInventory")
        self.verticalLayout.addWidget(self.pushButtonInventory)
        self.pushButtonStatistic = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButtonStatistic.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButtonStatistic.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.pushButtonStatistic.setToolTipDuration(0)
        self.pushButtonStatistic.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButtonStatistic.setAutoFillBackground(False)
        self.pushButtonStatistic.setStyleSheet("font: 63 12pt \"Montserrat SemiBold\";\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid #9b9fa2;\n"
"color: rgb(155, 159, 162);")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("C:\\Users\\Nicolee\\Coding\\Final_KTLT\\USER_INTERFACE\\Import\\../../RESOURCE/ICON/statis.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonStatistic.setIcon(icon7)
        self.pushButtonStatistic.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonStatistic.setObjectName("pushButtonStatistic")
        self.verticalLayout.addWidget(self.pushButtonStatistic)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, -12, 1393, 817))
        self.label_2.setStyleSheet("background-color: rgb(242, 248, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(264, 24, 601, 109))
        self.groupBox_2.setStyleSheet("padding: 5px;\n"
"border-radius: 10px;\n"
"color: rgb(155, 159, 162);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 25 10pt \"Montserrat Light\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(156, 36, 361, 61))
        self.lineEdit.setStyleSheet("background-color: rgb(242, 248, 255);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";\n"
"padding: 10px;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(528, 36, 61, 61))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #35B6E8; /* Màu nền mặc định */\n"
"    border-radius: 10px; \n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8EDAF8; /* Màu khi di chuột */  \n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #35B6E8; /* Màu khi nhấn */\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 5px solid #8EDAF8; /* Viền khi nút được focus */ \n"
"}\n"
"")
        self.pushButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("C:\\Users\\Nicolee\\Coding\\Final_KTLT\\USER_INTERFACE\\Import\\../../RESOURCE/ICON/search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon8)
        self.pushButton.setIconSize(QtCore.QSize(25, 25))
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(12, 36, 133, 61))
        self.comboBox.setStyleSheet("background-color: rgb(242, 248, 255);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";\n"
"padding: 10px;")
        self.comboBox.setEditable(False)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(264, 143, 601, 553))
        self.tableWidget.setToolTip("")
        self.tableWidget.setStyleSheet("padding: 5px;\n"
"border-radius: 10px;\n"
"color: rgb(14, 23, 67);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 57 10pt \"Montserrat Medium\";")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(36, 36, 205, 61))
        self.label_4.setStyleSheet("color: rgb(53, 182, 232);\n"
"font: 87 30pt \"Montserrat Black\";")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(36, 96, 205, 37))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 63 15pt \"Montserrat SemiBold\";\n"
"background-color: rgb(5, 129, 249);")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 720, 157, 61))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #FFFFFF; /* Màu nền mặc định */\n"
"    color: #D23435;\n"
"    font: 8120 17pt \"Montserrat Bold\";\n"
"    border-radius: 10px; \n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #D23435;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #D23435; /* Màu khi nhấn */\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 2px solid #D23435;\n"
"}\n"
"")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("C:\\Users\\Nicolee\\Coding\\Final_KTLT\\USER_INTERFACE\\Import\\../../RESOURCE/ICON/turnoff.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon9)
        self.pushButton_2.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(264, 708, 601, 109))
        self.label_3.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(336, 732, 457, 52))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(250, 50))
        self.lineEdit_2.setStyleSheet("background-color: rgb(242, 248, 255);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";\n"
"padding: 10px;\n"
"border-radius: 10px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_3.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    font: 57 12pt \"Montserrat Medium\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #35B6E8; /* Màu nền mặc định */\n"
"    border-radius: 10px; \n"
"    padding: 1px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8EDAF8; /* Màu khi di chuột */  \n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #35B6E8; /* Màu khi nhấn */\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 5px solid #8EDAF8; /* Viền khi nút được focus */ \n"
"}\n"
"")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("C:\\Users\\Nicolee\\Coding\\Final_KTLT\\USER_INTERFACE\\Import\\../../RESOURCE/ICON/tick.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon10)
        self.pushButton_3.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(876, 24, 493, 793))
        self.label_6.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(891, 36, 457, 97))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_7 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_7.setStyleSheet("color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";")
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_8.setStyleSheet("\n"
"color: rgb(157, 167, 220);\n"
"font: 57 12pt \"Montserrat Medium\";")
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_8)
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.formLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBox_2)
        self.label_9 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_9.setStyleSheet("color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";")
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_10.setStyleSheet("color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";")
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_11.setStyleSheet("\n"
"color: rgb(157, 167, 220);\n"
"font: 57 12pt \"Montserrat Medium\";")
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_11)
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(888, 144, 457, 493))
        self.tableWidget_2.setToolTip("")
        self.tableWidget_2.setStyleSheet("padding: 5px;\n"
"border-radius: 10px;\n"
"color: rgb(14, 23, 67);\n"
"background-color: rgb(242, 242, 242);\n"
"font: 57 10pt \"Montserrat Medium\";\n"
"")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(888, 648, 457, 61))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.pushButton_5.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_5.setSizeIncrement(QtCore.QSize(200, 50))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    font: 57 12pt \"Montserrat Medium\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #62DE92; /* Màu nền mặc định */\n"
"    border-radius: 10px; \n"
"    padding: 1px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #BAECCD; /* Màu khi di chuột */  \n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #62DE92; /* Màu khi nhấn */\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 5px solid #62DE92; /* Viền khi nút được focus */ \n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.pushButton_4.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_4.setSizeIncrement(QtCore.QSize(200, 50))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    font: 57 12pt \"Montserrat Medium\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #9DA7DC; /* Màu nền mặc định */\n"
"    border-radius: 10px; \n"
"    padding: 1px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D8DDF8; /* Màu khi di chuột */  \n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #9DA7DC; /* Màu khi nhấn */\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 5px solid #9DA7DC; /* Viền khi nút được focus */ \n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.horizontalGroupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.horizontalGroupBox_3.setGeometry(QtCore.QRect(888, 720, 457, 80))
        self.horizontalGroupBox_3.setObjectName("horizontalGroupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_3)
        self.horizontalLayout_3.setContentsMargins(19, -1, 19, -1)
        self.horizontalLayout_3.setSpacing(9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_12 = QtWidgets.QLabel(parent=self.horizontalGroupBox_3)
        self.label_12.setStyleSheet("font: 63 14pt \"Montserrat SemiBold\";\n"
"color: rgb(229, 0, 0);")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(parent=self.horizontalGroupBox_3)
        self.label_13.setStyleSheet("font: 81 14pt \"Montserrat ExtraBold\";\n"
"color: rgb(229, 0, 0);")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.horizontalGroupBox_3)
        self.pushButton_6.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    font: 57 12pt \"Montserrat Medium\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #35B6E8; /* Màu nền mặc định */\n"
"    border-radius: 10px; \n"
"    padding: 1px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8EDAF8; /* Màu khi di chuột */  \n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #35B6E8; /* Màu khi nhấn */\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 5px solid #8EDAF8; /* Viền khi nút được focus */ \n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.label_2.raise_()
        self.label.raise_()
        self.verticalLayoutWidget.raise_()
        self.groupBox_2.raise_()
        self.tableWidget.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.pushButton_2.raise_()
        self.label_3.raise_()
        self.horizontalLayoutWidget.raise_()
        self.label_6.raise_()
        self.formLayoutWidget.raise_()
        self.tableWidget_2.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.horizontalGroupBox_3.raise_()
        MainWindowImport.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindowImport)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1389, 26))
        self.menubar.setObjectName("menubar")
        MainWindowImport.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindowImport)
        self.statusbar.setObjectName("statusbar")
        MainWindowImport.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowImport)
        QtCore.QMetaObject.connectSlotsByName(MainWindowImport)

    def retranslateUi(self, MainWindowImport):
        _translate = QtCore.QCoreApplication.translate
        MainWindowImport.setWindowTitle(_translate("MainWindowImport", "Import "))
        self.pushButtonProduct.setText(_translate("MainWindowImport", "  Product"))
        self.pushButtonAdmin.setText(_translate("MainWindowImport", "  Admin"))
        self.pushButtonVendor.setText(_translate("MainWindowImport", "  Vendor"))
        self.pushButtonImport.setText(_translate("MainWindowImport", "  Import"))
        self.pushButtonReceipt.setText(_translate("MainWindowImport", " Good rec."))
        self.pushButtonExport.setText(_translate("MainWindowImport", "  Export"))
        self.pushButtonInvoice.setText(_translate("MainWindowImport", "  Invoice"))
        self.pushButtonInventory.setText(_translate("MainWindowImport", " Inventory"))
        self.pushButtonStatistic.setText(_translate("MainWindowImport", "  Statistic"))
        self.groupBox_2.setTitle(_translate("MainWindowImport", "Search "))
        self.lineEdit.setPlaceholderText(_translate("MainWindowImport", "*Search term"))
        self.comboBox.setCurrentText(_translate("MainWindowImport", "All"))
        self.comboBox.setItemText(0, _translate("MainWindowImport", "All"))
        self.comboBox.setItemText(1, _translate("MainWindowImport", "ID"))
        self.comboBox.setItemText(2, _translate("MainWindowImport", "Title"))
        self.comboBox.setItemText(3, _translate("MainWindowImport", "Artist"))
        self.comboBox.setItemText(4, _translate("MainWindowImport", "Year"))
        self.comboBox.setItemText(5, _translate("MainWindowImport", "Category"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindowImport", "Album ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindowImport", "Title"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindowImport", "Stock"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindowImport", "Price"))
        self.label_4.setText(_translate("MainWindowImport", "00:00"))
        self.label_5.setText(_translate("MainWindowImport", "Hi Admin!"))
        self.pushButton_2.setText(_translate("MainWindowImport", "EXIT"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindowImport", "*Quantity"))
        self.pushButton_3.setText(_translate("MainWindowImport", " Add"))
        self.label_7.setText(_translate("MainWindowImport", "Good Receipt ID"))
        self.label_8.setText(_translate("MainWindowImport", "#0000"))
        self.label_9.setText(_translate("MainWindowImport", "Vendor"))
        self.label_10.setText(_translate("MainWindowImport", "Admin"))
        self.label_11.setText(_translate("MainWindowImport", "Admin"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindowImport", "Album ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindowImport", "Title"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindowImport", "Quantity"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindowImport", "Price"))
        self.pushButton_5.setText(_translate("MainWindowImport", "Edit Quantity"))
        self.pushButton_4.setText(_translate("MainWindowImport", "Delete"))
        self.label_12.setText(_translate("MainWindowImport", "Total Price = "))
        self.label_13.setText(_translate("MainWindowImport", "50000"))
        self.pushButton_6.setText(_translate("MainWindowImport", "Import "))
