# Form implementation generated from reading ui file 'C:\Users\Nicolee\Coding\Final_KTLT\USER_INTERFACE\Export\MainWindowExport.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindowExport(object):
    def setupUi(self, MainWindowExport):
        MainWindowExport.setObjectName("MainWindowExport")
        MainWindowExport.resize(1389, 855)
        MainWindowExport.setMaximumSize(QtCore.QSize(1920, 1080))
        MainWindowExport.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        MainWindowExport.setAutoFillBackground(False)
        MainWindowExport.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        MainWindowExport.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindowExport)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(24, 24, 229, 793))
        self.label.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(36, 180, 205, 517))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonProduct = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButtonProduct.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButtonProduct.setToolTipDuration(-1)
        self.pushButtonProduct.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButtonProduct.setAutoFillBackground(False)
        self.pushButtonProduct.setStyleSheet("font: 63 12pt \"Montserrat SemiBold\";\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid #9b9fa2;\n"
"color: rgb(155, 159, 162);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Nicolee\\Coding\\Final_KTLT\\USER_INTERFACE\\Export\\../../RESOURCE/ICON/album2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonProduct.setIcon(icon)
        self.pushButtonProduct.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonProduct.setObjectName("pushButtonProduct")
        self.verticalLayout.addWidget(self.pushButtonProduct)
        self.pushButtonAdmin = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButtonAdmin.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButtonAdmin.setToolTipDuration(-1)
        self.pushButtonAdmin.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButtonAdmin.setAutoFillBackground(False)
        self.pushButtonAdmin.setStyleSheet("font: 63 12pt \"Montserrat SemiBold\";\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid #9b9fa2;\n"
"color: rgb(155, 159, 162);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\Nicolee\\Coding\\Final_KTLT\\USER_INTERFACE\\Export\\../../RESOURCE/ICON/adm2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonAdmin.setIcon(icon1)
        self.pushButtonAdmin.setIconSize(QtCore.QSize(35, 35))
        self.pushButtonAdmin.setObjectName("pushButtonAdmin")
        self.verticalLayout.addWidget(self.pushButtonAdmin)
        self.pushButtonVendor = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButtonVendor.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButtonVendor.setToolTipDuration(-1)
        self.pushButtonVendor.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButtonVendor.setAutoFillBackground(False)
        self.pushButtonVendor.setStyleSheet("font: 63 12pt \"Montserrat SemiBold\";\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid #9b9fa2;\n"
"color: rgb(155, 159, 162);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\Nicolee\\Coding\\Final_KTLT\\USER_INTERFACE\\Export\\../../RESOURCE/ICON/vendor1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonVendor.setIcon(icon2)
        self.pushButtonVendor.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonVendor.setObjectName("pushButtonVendor")
        self.verticalLayout.addWidget(self.pushButtonVendor)
        self.pushButtonImport = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButtonImport.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButtonImport.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.pushButtonImport.setToolTipDuration(0)
        self.pushButtonImport.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButtonImport.setAutoFillBackground(False)
        self.pushButtonImport.setStyleSheet("font: 63 12pt \"Montserrat SemiBold\";\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid #9b9fa2;\n"
"color: rgb(155, 159, 162);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:\\Users\\Nicolee\\Coding\\Final_KTLT\\USER_INTERFACE\\Export\\../../RESOURCE/ICON/import.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonImport.setIcon(icon3)
        self.pushButtonImport.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonImport.setObjectName("pushButtonImport")
        self.verticalLayout.addWidget(self.pushButtonImport)
        self.pushButtonReceipt = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButtonReceipt.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButtonReceipt.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.pushButtonReceipt.setToolTipDuration(0)
        self.pushButtonReceipt.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButtonReceipt.setAutoFillBackground(False)
        self.pushButtonReceipt.setStyleSheet("font: 63 12pt \"Montserrat SemiBold\";\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid #9b9fa2;\n"
"color: rgb(155, 159, 162);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:\\Users\\Nicolee\\Coding\\Final_KTLT\\USER_INTERFACE\\Export\\../../RESOURCE/ICON/doc.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonReceipt.setIcon(icon4)
        self.pushButtonReceipt.setIconSize(QtCore.QSize(35, 35))
        self.pushButtonReceipt.setObjectName("pushButtonReceipt")
        self.verticalLayout.addWidget(self.pushButtonReceipt)
        self.pushButtonExport = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButtonExport.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButtonExport.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.pushButtonExport.setToolTipDuration(0)
        self.pushButtonExport.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButtonExport.setAutoFillBackground(False)
        self.pushButtonExport.setStyleSheet("font: 63 12pt \"Montserrat SemiBold\";\n"
"color: rgb(14, 23, 67);\n"
"background-color: rgb(242, 248, 255)")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:\\Users\\Nicolee\\Coding\\Final_KTLT\\USER_INTERFACE\\Export\\../../RESOURCE/ICON/export2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonExport.setIcon(icon5)
        self.pushButtonExport.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonExport.setObjectName("pushButtonExport")
        self.verticalLayout.addWidget(self.pushButtonExport)
        self.pushButtonInvoice = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButtonInvoice.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButtonInvoice.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.pushButtonInvoice.setToolTipDuration(0)
        self.pushButtonInvoice.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButtonInvoice.setAutoFillBackground(False)
        self.pushButtonInvoice.setStyleSheet("font: 63 12pt \"Montserrat SemiBold\";\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid #9b9fa2;\n"
"color: rgb(155, 159, 162);")
        self.pushButtonInvoice.setIcon(icon4)
        self.pushButtonInvoice.setIconSize(QtCore.QSize(35, 35))
        self.pushButtonInvoice.setObjectName("pushButtonInvoice")
        self.verticalLayout.addWidget(self.pushButtonInvoice)
        self.pushButtonInventory = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButtonInventory.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButtonInventory.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.pushButtonInventory.setToolTipDuration(0)
        self.pushButtonInventory.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButtonInventory.setAutoFillBackground(False)
        self.pushButtonInventory.setStyleSheet("font: 63 12pt \"Montserrat SemiBold\";\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid #9b9fa2;\n"
"color: rgb(155, 159, 162);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:\\Users\\Nicolee\\Coding\\Final_KTLT\\USER_INTERFACE\\Export\\../../RESOURCE/ICON/inventory.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonInventory.setIcon(icon6)
        self.pushButtonInventory.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonInventory.setObjectName("pushButtonInventory")
        self.verticalLayout.addWidget(self.pushButtonInventory)
        self.pushButtonStatistic = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButtonStatistic.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButtonStatistic.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.pushButtonStatistic.setToolTipDuration(0)
        self.pushButtonStatistic.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButtonStatistic.setAutoFillBackground(False)
        self.pushButtonStatistic.setStyleSheet("font: 63 12pt \"Montserrat SemiBold\";\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid #9b9fa2;\n"
"color: rgb(155, 159, 162);")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("C:\\Users\\Nicolee\\Coding\\Final_KTLT\\USER_INTERFACE\\Export\\../../RESOURCE/ICON/statis.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonStatistic.setIcon(icon7)
        self.pushButtonStatistic.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonStatistic.setObjectName("pushButtonStatistic")
        self.verticalLayout.addWidget(self.pushButtonStatistic)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, -12, 1393, 817))
        self.label_2.setStyleSheet("background-color: rgb(242, 248, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(264, 24, 601, 109))
        self.groupBox_2.setStyleSheet("padding: 5px;\n"
"border-radius: 10px;\n"
"color: rgb(155, 159, 162);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 25 10pt \"Montserrat Light\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEditSearch = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditSearch.setGeometry(QtCore.QRect(156, 36, 361, 61))
        self.lineEditSearch.setStyleSheet("background-color: rgb(242, 248, 255);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";\n"
"padding: 10px;")
        self.lineEditSearch.setText("")
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.pushButtonSearch = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonSearch.setGeometry(QtCore.QRect(528, 36, 61, 61))
        self.pushButtonSearch.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButtonSearch.setStyleSheet("QPushButton {\n"
"    background-color: #35B6E8; /* Màu nền mặc định */\n"
"    border-radius: 10px; \n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8EDAF8; /* Màu khi di chuột */  \n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #35B6E8; /* Màu khi nhấn */\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 5px solid #8EDAF8; /* Viền khi nút được focus */ \n"
"}\n"
"")
        self.pushButtonSearch.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("C:\\Users\\Nicolee\\Coding\\Final_KTLT\\USER_INTERFACE\\Export\\../../RESOURCE/ICON/search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSearch.setIcon(icon8)
        self.pushButtonSearch.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.comboBoxSearch = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.comboBoxSearch.setGeometry(QtCore.QRect(12, 36, 133, 61))
        self.comboBoxSearch.setStyleSheet("background-color: rgb(242, 248, 255);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";\n"
"padding: 10px;")
        self.comboBoxSearch.setEditable(False)
        self.comboBoxSearch.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.comboBoxSearch.setObjectName("comboBoxSearch")
        self.comboBoxSearch.addItem("")
        self.comboBoxSearch.addItem("")
        self.comboBoxSearch.addItem("")
        self.comboBoxSearch.addItem("")
        self.comboBoxSearch.addItem("")
        self.comboBoxSearch.addItem("")
        self.tableWidgetDefault = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidgetDefault.setGeometry(QtCore.QRect(264, 143, 601, 553))
        self.tableWidgetDefault.setToolTip("")
        self.tableWidgetDefault.setStyleSheet("padding: 5px;\n"
"border-radius: 10px;\n"
"color: rgb(14, 23, 67);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 57 10pt \"Montserrat Medium\";")
        self.tableWidgetDefault.setObjectName("tableWidgetDefault")
        self.tableWidgetDefault.setColumnCount(4)
        self.tableWidgetDefault.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDefault.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDefault.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDefault.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDefault.setHorizontalHeaderItem(3, item)
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(36, 36, 205, 61))
        self.label_4.setStyleSheet("color: rgb(53, 182, 232);\n"
"font: 87 30pt \"Montserrat Black\";")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(36, 96, 205, 37))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 63 15pt \"Montserrat SemiBold\";\n"
"background-color: rgb(5, 129, 249);")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonExit.setGeometry(QtCore.QRect(60, 720, 157, 61))
        self.pushButtonExit.setStyleSheet("QPushButton {\n"
"    background-color: #FFFFFF; /* Màu nền mặc định */\n"
"    color: #D23435;\n"
"    font: 8120 17pt \"Montserrat Bold\";\n"
"    border-radius: 10px; \n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #D23435;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #D23435; /* Màu khi nhấn */\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 2px solid #D23435;\n"
"}\n"
"")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("C:\\Users\\Nicolee\\Coding\\Final_KTLT\\USER_INTERFACE\\Export\\../../RESOURCE/ICON/turnoff.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonExit.setIcon(icon9)
        self.pushButtonExit.setIconSize(QtCore.QSize(35, 35))
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(264, 708, 601, 109))
        self.label_3.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(336, 732, 457, 52))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditQuantity = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.lineEditQuantity.setMaximumSize(QtCore.QSize(250, 50))
        self.lineEditQuantity.setStyleSheet("background-color: rgb(242, 248, 255);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";\n"
"padding: 10px;\n"
"border-radius: 10px;")
        self.lineEditQuantity.setObjectName("lineEditQuantity")
        self.horizontalLayout.addWidget(self.lineEditQuantity)
        self.pushButtonAdd = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButtonAdd.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButtonAdd.setStyleSheet("QPushButton {\n"
"    font: 57 12pt \"Montserrat Medium\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #35B6E8; /* Màu nền mặc định */\n"
"    border-radius: 10px; \n"
"    padding: 1px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8EDAF8; /* Màu khi di chuột */  \n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #35B6E8; /* Màu khi nhấn */\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 5px solid #8EDAF8; /* Viền khi nút được focus */ \n"
"}\n"
"")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("C:\\Users\\Nicolee\\Coding\\Final_KTLT\\USER_INTERFACE\\Export\\../../RESOURCE/ICON/tick.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonAdd.setIcon(icon10)
        self.pushButtonAdd.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.horizontalLayout.addWidget(self.pushButtonAdd)
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(876, 24, 493, 793))
        self.label_6.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(891, 48, 457, 85))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_7 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_7.setStyleSheet("color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";")
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_7)
        self.labelGoodInvoiceID = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.labelGoodInvoiceID.setStyleSheet("\n"
"color: rgb(157, 167, 220);\n"
"font: 57 12pt \"Montserrat Medium\";")
        self.labelGoodInvoiceID.setObjectName("labelGoodInvoiceID")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.labelGoodInvoiceID)
        self.label_10 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_10.setStyleSheet("color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";")
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_10)
        self.labelAdminName = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.labelAdminName.setStyleSheet("\n"
"color: rgb(157, 167, 220);\n"
"font: 57 12pt \"Montserrat Medium\";")
        self.labelAdminName.setObjectName("labelAdminName")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.labelAdminName)
        self.tableWidgetExport = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidgetExport.setGeometry(QtCore.QRect(888, 144, 457, 493))
        self.tableWidgetExport.setToolTip("")
        self.tableWidgetExport.setStyleSheet("padding: 5px;\n"
"border-radius: 10px;\n"
"color: rgb(14, 23, 67);\n"
"background-color: rgb(242, 242, 242);\n"
"font: 57 10pt \"Montserrat Medium\";\n"
"")
        self.tableWidgetExport.setObjectName("tableWidgetExport")
        self.tableWidgetExport.setColumnCount(4)
        self.tableWidgetExport.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetExport.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetExport.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetExport.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetExport.setHorizontalHeaderItem(3, item)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(888, 648, 457, 61))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonEdit = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.pushButtonEdit.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButtonEdit.setSizeIncrement(QtCore.QSize(200, 50))
        self.pushButtonEdit.setStyleSheet("QPushButton {\n"
"    font: 57 12pt \"Montserrat Medium\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #62DE92; /* Màu nền mặc định */\n"
"    border-radius: 10px; \n"
"    padding: 1px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #BAECCD; /* Màu khi di chuột */  \n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #62DE92; /* Màu khi nhấn */\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 5px solid #62DE92; /* Viền khi nút được focus */ \n"
"}\n"
"")
        self.pushButtonEdit.setObjectName("pushButtonEdit")
        self.horizontalLayout_2.addWidget(self.pushButtonEdit)
        self.pushButtonDelete = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.pushButtonDelete.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButtonDelete.setSizeIncrement(QtCore.QSize(200, 50))
        self.pushButtonDelete.setStyleSheet("QPushButton {\n"
"    font: 57 12pt \"Montserrat Medium\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #9DA7DC; /* Màu nền mặc định */\n"
"    border-radius: 10px; \n"
"    padding: 1px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D8DDF8; /* Màu khi di chuột */  \n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #9DA7DC; /* Màu khi nhấn */\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 5px solid #9DA7DC; /* Viền khi nút được focus */ \n"
"}\n"
"")
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.horizontalLayout_2.addWidget(self.pushButtonDelete)
        self.horizontalGroupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.horizontalGroupBox_3.setGeometry(QtCore.QRect(888, 720, 457, 80))
        self.horizontalGroupBox_3.setObjectName("horizontalGroupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_3)
        self.horizontalLayout_3.setContentsMargins(19, -1, 19, -1)
        self.horizontalLayout_3.setSpacing(9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_12 = QtWidgets.QLabel(parent=self.horizontalGroupBox_3)
        self.label_12.setStyleSheet("font: 63 14pt \"Montserrat SemiBold\";\n"
"color: rgb(229, 0, 0);")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.labelTotalPrice = QtWidgets.QLabel(parent=self.horizontalGroupBox_3)
        self.labelTotalPrice.setStyleSheet("font: 81 14pt \"Montserrat ExtraBold\";\n"
"color: rgb(229, 0, 0);")
        self.labelTotalPrice.setObjectName("labelTotalPrice")
        self.horizontalLayout_3.addWidget(self.labelTotalPrice)
        self.pushButtonExportEx = QtWidgets.QPushButton(parent=self.horizontalGroupBox_3)
        self.pushButtonExportEx.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButtonExportEx.setStyleSheet("QPushButton {\n"
"    font: 57 12pt \"Montserrat Medium\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #35B6E8; /* Màu nền mặc định */\n"
"    border-radius: 10px; \n"
"    padding: 1px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8EDAF8; /* Màu khi di chuột */  \n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #35B6E8; /* Màu khi nhấn */\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 5px solid #8EDAF8; /* Viền khi nút được focus */ \n"
"}\n"
"")
        self.pushButtonExportEx.setObjectName("pushButtonExportEx")
        self.horizontalLayout_3.addWidget(self.pushButtonExportEx)
        self.label_2.raise_()
        self.label.raise_()
        self.verticalLayoutWidget.raise_()
        self.groupBox_2.raise_()
        self.tableWidgetDefault.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.pushButtonExit.raise_()
        self.label_3.raise_()
        self.horizontalLayoutWidget.raise_()
        self.label_6.raise_()
        self.formLayoutWidget.raise_()
        self.tableWidgetExport.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.horizontalGroupBox_3.raise_()
        MainWindowExport.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindowExport)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1389, 26))
        self.menubar.setObjectName("menubar")
        MainWindowExport.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindowExport)
        self.statusbar.setObjectName("statusbar")
        MainWindowExport.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowExport)
        QtCore.QMetaObject.connectSlotsByName(MainWindowExport)

    def retranslateUi(self, MainWindowExport):
        _translate = QtCore.QCoreApplication.translate
        MainWindowExport.setWindowTitle(_translate("MainWindowExport", "Export "))
        self.pushButtonProduct.setText(_translate("MainWindowExport", "  Product"))
        self.pushButtonAdmin.setText(_translate("MainWindowExport", "  Admin"))
        self.pushButtonVendor.setText(_translate("MainWindowExport", "  Vendor"))
        self.pushButtonImport.setText(_translate("MainWindowExport", "  Import"))
        self.pushButtonReceipt.setText(_translate("MainWindowExport", " Good rec."))
        self.pushButtonExport.setText(_translate("MainWindowExport", "  Export"))
        self.pushButtonInvoice.setText(_translate("MainWindowExport", "  Invoice"))
        self.pushButtonInventory.setText(_translate("MainWindowExport", " Inventory"))
        self.pushButtonStatistic.setText(_translate("MainWindowExport", "  Statistic"))
        self.groupBox_2.setTitle(_translate("MainWindowExport", "Search "))
        self.lineEditSearch.setPlaceholderText(_translate("MainWindowExport", "*Search term"))
        self.comboBoxSearch.setCurrentText(_translate("MainWindowExport", "All"))
        self.comboBoxSearch.setItemText(0, _translate("MainWindowExport", "All"))
        self.comboBoxSearch.setItemText(1, _translate("MainWindowExport", "ID"))
        self.comboBoxSearch.setItemText(2, _translate("MainWindowExport", "Title"))
        self.comboBoxSearch.setItemText(3, _translate("MainWindowExport", "Artist"))
        self.comboBoxSearch.setItemText(4, _translate("MainWindowExport", "Year"))
        self.comboBoxSearch.setItemText(5, _translate("MainWindowExport", "Category"))
        item = self.tableWidgetDefault.horizontalHeaderItem(0)
        item.setText(_translate("MainWindowExport", "Album ID"))
        item = self.tableWidgetDefault.horizontalHeaderItem(1)
        item.setText(_translate("MainWindowExport", "Title"))
        item = self.tableWidgetDefault.horizontalHeaderItem(2)
        item.setText(_translate("MainWindowExport", "Stock"))
        item = self.tableWidgetDefault.horizontalHeaderItem(3)
        item.setText(_translate("MainWindowExport", "Price"))
        self.label_4.setText(_translate("MainWindowExport", "00:00"))
        self.label_5.setText(_translate("MainWindowExport", "Hi Admin!"))
        self.pushButtonExit.setText(_translate("MainWindowExport", "EXIT"))
        self.lineEditQuantity.setPlaceholderText(_translate("MainWindowExport", "*Quantity"))
        self.pushButtonAdd.setText(_translate("MainWindowExport", " Add"))
        self.label_7.setText(_translate("MainWindowExport", "Good Invoice ID"))
        self.labelGoodInvoiceID.setText(_translate("MainWindowExport", "#0000"))
        self.label_10.setText(_translate("MainWindowExport", "Admin"))
        self.labelAdminName.setText(_translate("MainWindowExport", "Admin"))
        item = self.tableWidgetExport.horizontalHeaderItem(0)
        item.setText(_translate("MainWindowExport", "Album ID"))
        item = self.tableWidgetExport.horizontalHeaderItem(1)
        item.setText(_translate("MainWindowExport", "Title"))
        item = self.tableWidgetExport.horizontalHeaderItem(2)
        item.setText(_translate("MainWindowExport", "Quantity"))
        item = self.tableWidgetExport.horizontalHeaderItem(3)
        item.setText(_translate("MainWindowExport", "Price"))
        self.pushButtonEdit.setText(_translate("MainWindowExport", "Edit Quantity"))
        self.pushButtonDelete.setText(_translate("MainWindowExport", "Delete"))
        self.label_12.setText(_translate("MainWindowExport", "Total Price = "))
        self.labelTotalPrice.setText(_translate("MainWindowExport", "50000"))
        self.pushButtonExportEx.setText(_translate("MainWindowExport", "Export "))
