# Form implementation generated from reading ui file 'D:\code hk2\Final_KTLT\USER_INTERFACE\Product\MainWindowAddProduct.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindowAddAdmin(object):
    def setupUi(self, MainWindowAddAdmin):
        MainWindowAddAdmin.setObjectName("MainWindowAddAdmin")
        MainWindowAddAdmin.resize(809, 627)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindowAddAdmin)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 110, 698, 351))
        self.groupBox.setMaximumSize(QtCore.QSize(1000, 400))
        self.groupBox.setStyleSheet("padding: 5px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(77, 77, 77);\n"
"font: 18 8pt \"Montserrat Light\";")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 80, 179, 195))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_2.setStyleSheet("color: rgb(14, 23, 67);\n"
"font: 57 10pt \"Montserrat Medium\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEditProductID = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.lineEditProductID.setMaximumSize(QtCore.QSize(1000, 100))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lineEditProductID.setFont(font)
        self.lineEditProductID.setStyleSheet("background-color: rgb(242, 248, 255);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 10pt \"Montserrat Medium\";\n"
"padding: 10px;")
        self.lineEditProductID.setObjectName("lineEditProductID")
        self.verticalLayout.addWidget(self.lineEditProductID)
        self.label_3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_3.setStyleSheet("color: rgb(14, 23, 67);\n"
"font: 57 10pt \"Montserrat Medium\";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEditTitle = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.lineEditTitle.setMaximumSize(QtCore.QSize(1000, 100))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lineEditTitle.setFont(font)
        self.lineEditTitle.setStyleSheet("background-color: rgb(242, 248, 255);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 10pt \"Montserrat Medium\";\n"
"padding: 10px;")
        self.lineEditTitle.setObjectName("lineEditTitle")
        self.verticalLayout.addWidget(self.lineEditTitle)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(260, 80, 179, 195))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_9.setStyleSheet("color: rgb(14, 23, 67);\n"
"font: 57 10pt \"Montserrat Medium\";")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.lineEditYear = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.lineEditYear.setMaximumSize(QtCore.QSize(1000, 100))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lineEditYear.setFont(font)
        self.lineEditYear.setStyleSheet("background-color: rgb(242, 248, 255);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 10pt \"Montserrat Medium\";\n"
"padding: 10px;")
        self.lineEditYear.setObjectName("lineEditYear")
        self.verticalLayout_2.addWidget(self.lineEditYear)
        self.label_10 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_10.setStyleSheet("color: rgb(14, 23, 67);\n"
"font: 57 10pt \"Montserrat Medium\";")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.lineEditCategory = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.lineEditCategory.setMaximumSize(QtCore.QSize(1000, 100))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lineEditCategory.setFont(font)
        self.lineEditCategory.setStyleSheet("background-color: rgb(242, 248, 255);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 10pt \"Montserrat Medium\";\n"
"padding: 10px;")
        self.lineEditCategory.setObjectName("lineEditCategory")
        self.verticalLayout_2.addWidget(self.lineEditCategory)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=self.groupBox)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(490, 80, 179, 195))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_13 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_13.setStyleSheet("color: rgb(14, 23, 67);\n"
"font: 57 10pt \"Montserrat Medium\";")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.lineEditCategory_2 = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_3)
        self.lineEditCategory_2.setMaximumSize(QtCore.QSize(1000, 100))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lineEditCategory_2.setFont(font)
        self.lineEditCategory_2.setStyleSheet("background-color: rgb(242, 248, 255);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 10pt \"Montserrat Medium\";\n"
"padding: 10px;")
        self.lineEditCategory_2.setObjectName("lineEditCategory_2")
        self.verticalLayout_3.addWidget(self.lineEditCategory_2)
        self.label_14 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_14.setStyleSheet("color: rgb(14, 23, 67);\n"
"font: 57 10pt \"Montserrat Medium\";")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14)
        self.lineEditPrice_2 = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_3)
        self.lineEditPrice_2.setMaximumSize(QtCore.QSize(1000, 100))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lineEditPrice_2.setFont(font)
        self.lineEditPrice_2.setStyleSheet("background-color: rgb(242, 248, 255);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 10pt \"Montserrat Medium\";\n"
"padding: 10px;")
        self.lineEditPrice_2.setObjectName("lineEditPrice_2")
        self.verticalLayout_3.addWidget(self.lineEditPrice_2)
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 771, 571))
        self.label_8.setStyleSheet("background-color: rgb(242, 248, 255);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 771, 71))
        self.label.setStyleSheet("  background-color: #0581F9;\n"
"font: 75 24pt \"CocogooseProTrial Bold\";\n"
"    padding: 5px;\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"")
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 470, 701, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonSave = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButtonSave.setMaximumSize(QtCore.QSize(170, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButtonSave.setFont(font)
        self.pushButtonSave.setToolTipDuration(-1)
        self.pushButtonSave.setStyleSheet("QPushButton {\n"
"    background-color: #FF2090; /* Màu nền mặc định */\n"
"\n"
"    border-radius: 10px; \n"
"    padding: 5px;\n"
" \n"
"    font: 57 14pt \"Montserrat Medium\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFA2D1; /* Màu khi di chuột */  \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FF2090; /* Màu khi nhấn */\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 5px solid #FFA2D1; /* Viền khi nút được focus */ \n"
"}\n"
"\n"
"\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\code hk2\\Final_KTLT\\USER_INTERFACE\\Product\\../../RESOURCE/ICON/1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSave.setIcon(icon)
        self.pushButtonSave.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayout.addWidget(self.pushButtonSave)
        self.pushButtonCancel = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButtonCancel.setMaximumSize(QtCore.QSize(170, 50))
        self.pushButtonCancel.setStyleSheet("QPushButton {\n"
"    background-color: #35B6E8; /* Màu nền mặc định */\n"
"\n"
"    border-radius: 10px; \n"
"    padding: 5px;\n"
" \n"
"    font: 57 14pt \"Montserrat Medium\";\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A3E3FC; /* Màu khi di chuột */  \n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #35B6E8; /* Màu khi nhấn */\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 5px solid #A3E3FC; /* Viền khi nút được focus */ \n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\code hk2\\Final_KTLT\\USER_INTERFACE\\Product\\../../RESOURCE/ICON/cancel.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonCancel.setIcon(icon1)
        self.pushButtonCancel.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.label_8.raise_()
        self.groupBox.raise_()
        self.label.raise_()
        self.horizontalLayoutWidget.raise_()
        MainWindowAddAdmin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindowAddAdmin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 809, 26))
        self.menubar.setObjectName("menubar")
        MainWindowAddAdmin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindowAddAdmin)
        self.statusbar.setObjectName("statusbar")
        MainWindowAddAdmin.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowAddAdmin)
        QtCore.QMetaObject.connectSlotsByName(MainWindowAddAdmin)

    def retranslateUi(self, MainWindowAddAdmin):
        _translate = QtCore.QCoreApplication.translate
        MainWindowAddAdmin.setWindowTitle(_translate("MainWindowAddAdmin", "Add new admin"))
        self.label_2.setText(_translate("MainWindowAddAdmin", "Product_ID:"))
        self.label_3.setText(_translate("MainWindowAddAdmin", "Title:"))
        self.label_9.setText(_translate("MainWindowAddAdmin", "Year:"))
        self.label_10.setText(_translate("MainWindowAddAdmin", "Category:"))
        self.label_13.setText(_translate("MainWindowAddAdmin", "Artist:"))
        self.label_14.setText(_translate("MainWindowAddAdmin", "Price:"))
        self.label.setText(_translate("MainWindowAddAdmin", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Add new album</span></p></body></html>"))
        self.pushButtonSave.setToolTip(_translate("MainWindowAddAdmin", "<html><head/><body><p><span style=\" font-size:12pt; color:#ff2090;\">New</span></p></body></html>"))
        self.pushButtonSave.setText(_translate("MainWindowAddAdmin", " Save"))
        self.pushButtonCancel.setToolTip(_translate("MainWindowAddAdmin", "<html><head/><body><p><span style=\" font-size:12pt; color:#35b6e8;\">Edit</span></p></body></html>"))
        self.pushButtonCancel.setText(_translate("MainWindowAddAdmin", " Cancel"))
