# Form implementation generated from reading ui file 'D:\code hk2\Final_KTLT\USER_INTERFACE\Invoice\MainWindowEditInvoice.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_MainWindowImport(object):
    def setupUi(self, MainWindowImport):
        MainWindowImport.setObjectName("MainWindowImport")
        MainWindowImport.resize(1137, 848)
        MainWindowImport.setMaximumSize(QtCore.QSize(1920, 1080))
        MainWindowImport.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        MainWindowImport.setAutoFillBackground(False)
        MainWindowImport.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        MainWindowImport.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindowImport)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 10, 1081, 781))
        self.label_2.setStyleSheet("background-color: rgb(242, 248, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(60, 24, 541, 91))
        self.groupBox_2.setStyleSheet("padding: 5px;\n"
"border-radius: 10px;\n"
"color: rgb(155, 159, 162);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 25 10pt \"Montserrat Light\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEditSearch = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditSearch.setGeometry(QtCore.QRect(140, 36, 331, 41))
        self.lineEditSearch.setStyleSheet("background-color: rgb(242, 248, 255);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";\n"
"padding: 10px;")
        self.lineEditSearch.setText("")
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.pushButtonSearch = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonSearch.setGeometry(QtCore.QRect(490, 36, 41, 41))
        self.pushButtonSearch.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButtonSearch.setStyleSheet("QPushButton {\n"
"    background-color: #35B6E8; /* Màu nền mặc định */\n"
"    border-radius: 10px; \n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8EDAF8; /* Màu khi di chuột */  \n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #35B6E8; /* Màu khi nhấn */\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 5px solid #8EDAF8; /* Viền khi nút được focus */ \n"
"}\n"
"")
        self.pushButtonSearch.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\code hk2\\Final_KTLT\\USER_INTERFACE\\Invoice\\../../RESOURCE/ICON/search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSearch.setIcon(icon)
        self.pushButtonSearch.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.comboBoxSearch = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.comboBoxSearch.setGeometry(QtCore.QRect(12, 36, 101, 41))
        self.comboBoxSearch.setStyleSheet("background-color: rgb(242, 248, 255);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";\n"
"padding: 10px;")
        self.comboBoxSearch.setEditable(False)
        self.comboBoxSearch.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.comboBoxSearch.setObjectName("comboBoxSearch")
        self.comboBoxSearch.addItem("")
        self.comboBoxSearch.addItem("")
        self.comboBoxSearch.addItem("")
        self.comboBoxSearch.addItem("")
        self.comboBoxSearch.addItem("")
        self.comboBoxSearch.addItem("")
        self.tableWidgetDefault = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidgetDefault.setGeometry(QtCore.QRect(60, 130, 541, 553))
        self.tableWidgetDefault.setToolTip("")
        self.tableWidgetDefault.setStyleSheet("padding: 5px;\n"
"border-radius: 10px;\n"
"color: rgb(14, 23, 67);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 57 10pt \"Montserrat Medium\";")
        self.tableWidgetDefault.setObjectName("tableWidgetDefault")
        self.tableWidgetDefault.setColumnCount(4)
        self.tableWidgetDefault.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDefault.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDefault.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDefault.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDefault.setHorizontalHeaderItem(3, item)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 690, 541, 91))
        self.label_3.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(100, 710, 457, 52))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditQuantity = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.lineEditQuantity.setMaximumSize(QtCore.QSize(250, 50))
        self.lineEditQuantity.setStyleSheet("background-color: rgb(242, 248, 255);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";\n"
"padding: 10px;\n"
"border-radius: 10px;")
        self.lineEditQuantity.setObjectName("lineEditQuantity")
        self.horizontalLayout.addWidget(self.lineEditQuantity)
        self.pushButtonAdd = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButtonAdd.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButtonAdd.setStyleSheet("QPushButton {\n"
"    font: 57 12pt \"Montserrat Medium\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #35B6E8; /* Màu nền mặc định */\n"
"    border-radius: 10px; \n"
"    padding: 1px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8EDAF8; /* Màu khi di chuột */  \n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #35B6E8; /* Màu khi nhấn */\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 5px solid #8EDAF8; /* Viền khi nút được focus */ \n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\code hk2\\Final_KTLT\\USER_INTERFACE\\Invoice\\../../RESOURCE/ICON/tick.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonAdd.setIcon(icon1)
        self.pushButtonAdd.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.horizontalLayout.addWidget(self.pushButtonAdd)
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(610, 22, 493, 761))
        self.label_6.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(623, 40, 431, 111))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_7 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_7.setStyleSheet("color: rgb(14, 23, 67);\n"
"font: 57 10pt \"Montserrat Medium\";")
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_7)
        self.labelGoodInvoiceID = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.labelGoodInvoiceID.setStyleSheet("\n"
"color: rgb(157, 167, 220);\n"
"font: 57 10pt \"Montserrat Medium\";")
        self.labelGoodInvoiceID.setObjectName("labelGoodInvoiceID")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.labelGoodInvoiceID)
        self.label_10 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_10.setStyleSheet("color: rgb(14, 23, 67);\n"
"font: 57 10pt \"Montserrat Medium\";")
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_10)
        self.labelAdminName = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.labelAdminName.setStyleSheet("\n"
"color: rgb(157, 167, 220);\n"
"font: 57 10pt \"Montserrat Medium\";")
        self.labelAdminName.setObjectName("labelAdminName")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.labelAdminName)
        self.label_9 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_9.setStyleSheet("color: rgb(14, 23, 67);\n"
"font: 57 10pt \"Montserrat Medium\";")
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_9)
        self.comboBoxVendor = QtWidgets.QComboBox(parent=self.formLayoutWidget)
        self.comboBoxVendor.setObjectName("comboBoxVendor")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBoxVendor)
        self.tableWidgetImport = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidgetImport.setGeometry(QtCore.QRect(620, 150, 441, 491))
        self.tableWidgetImport.setToolTip("")
        self.tableWidgetImport.setStyleSheet("padding: 5px;\n"
"border-radius: 10px;\n"
"color: rgb(14, 23, 67);\n"
"background-color: rgb(242, 242, 242);\n"
"font: 57 10pt \"Montserrat Medium\";\n"
"")
        self.tableWidgetImport.setObjectName("tableWidgetImport")
        self.tableWidgetImport.setColumnCount(4)
        self.tableWidgetImport.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetImport.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetImport.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetImport.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetImport.setHorizontalHeaderItem(3, item)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(620, 650, 441, 61))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonEdit = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.pushButtonEdit.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButtonEdit.setSizeIncrement(QtCore.QSize(200, 50))
        self.pushButtonEdit.setStyleSheet("QPushButton {\n"
"    font: 57 12pt \"Montserrat Medium\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #62DE92; /* Màu nền mặc định */\n"
"    border-radius: 10px; \n"
"    padding: 1px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #BAECCD; /* Màu khi di chuột */  \n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #62DE92; /* Màu khi nhấn */\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 5px solid #62DE92; /* Viền khi nút được focus */ \n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\code hk2\\Final_KTLT\\USER_INTERFACE\\Invoice\\../../RESOURCE/ICON/edit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonEdit.setIcon(icon2)
        self.pushButtonEdit.setObjectName("pushButtonEdit")
        self.horizontalLayout_2.addWidget(self.pushButtonEdit)
        self.pushButtonDelete = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.pushButtonDelete.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButtonDelete.setSizeIncrement(QtCore.QSize(200, 50))
        self.pushButtonDelete.setStyleSheet("QPushButton {\n"
"    font: 57 12pt \"Montserrat Medium\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #9DA7DC; /* Màu nền mặc định */\n"
"    border-radius: 10px; \n"
"    padding: 1px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D8DDF8; /* Màu khi di chuột */  \n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #9DA7DC; /* Màu khi nhấn */\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 5px solid #9DA7DC; /* Viền khi nút được focus */ \n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:\\code hk2\\Final_KTLT\\USER_INTERFACE\\Invoice\\../../RESOURCE/ICON/delete.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonDelete.setIcon(icon3)
        self.pushButtonDelete.setIconSize(QtCore.QSize(50, 25))
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.horizontalLayout_2.addWidget(self.pushButtonDelete)
        self.horizontalGroupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.horizontalGroupBox_3.setGeometry(QtCore.QRect(620, 720, 441, 51))
        self.horizontalGroupBox_3.setObjectName("horizontalGroupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_3)
        self.horizontalLayout_3.setContentsMargins(19, -1, 19, -1)
        self.horizontalLayout_3.setSpacing(9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_12 = QtWidgets.QLabel(parent=self.horizontalGroupBox_3)
        self.label_12.setStyleSheet("font: 63 14pt \"Montserrat SemiBold\";\n"
"color: rgb(229, 0, 0);")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.labelTotalPrice = QtWidgets.QLabel(parent=self.horizontalGroupBox_3)
        self.labelTotalPrice.setStyleSheet("font: 81 14pt \"Montserrat ExtraBold\";\n"
"color: rgb(229, 0, 0);")
        self.labelTotalPrice.setObjectName("labelTotalPrice")
        self.horizontalLayout_3.addWidget(self.labelTotalPrice)
        self.pushButtonImportEx = QtWidgets.QPushButton(parent=self.horizontalGroupBox_3)
        self.pushButtonImportEx.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButtonImportEx.setStyleSheet("QPushButton {\n"
"    font: 57 12pt \"Montserrat Medium\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #35B6E8; /* Màu nền mặc định */\n"
"    border-radius: 10px; \n"
"    padding: 1px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8EDAF8; /* Màu khi di chuột */  \n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #35B6E8; /* Màu khi nhấn */\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 5px solid #8EDAF8; /* Viền khi nút được focus */ \n"
"}\n"
"")
        self.pushButtonImportEx.setObjectName("pushButtonImportEx")
        self.horizontalLayout_3.addWidget(self.pushButtonImportEx)
        MainWindowImport.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindowImport)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1137, 26))
        self.menubar.setObjectName("menubar")
        MainWindowImport.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindowImport)
        self.statusbar.setObjectName("statusbar")
        MainWindowImport.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowImport)
        QtCore.QMetaObject.connectSlotsByName(MainWindowImport)

    def retranslateUi(self, MainWindowImport):
        _translate = QtCore.QCoreApplication.translate
        MainWindowImport.setWindowTitle(_translate("MainWindowImport", "Import "))
        self.groupBox_2.setTitle(_translate("MainWindowImport", "Search "))
        self.lineEditSearch.setPlaceholderText(_translate("MainWindowImport", "*Search term"))
        self.comboBoxSearch.setCurrentText(_translate("MainWindowImport", "All"))
        self.comboBoxSearch.setItemText(0, _translate("MainWindowImport", "All"))
        self.comboBoxSearch.setItemText(1, _translate("MainWindowImport", "ID"))
        self.comboBoxSearch.setItemText(2, _translate("MainWindowImport", "Title"))
        self.comboBoxSearch.setItemText(3, _translate("MainWindowImport", "Artist"))
        self.comboBoxSearch.setItemText(4, _translate("MainWindowImport", "Year"))
        self.comboBoxSearch.setItemText(5, _translate("MainWindowImport", "Category"))
        item = self.tableWidgetDefault.horizontalHeaderItem(0)
        item.setText(_translate("MainWindowImport", "Album ID"))
        item = self.tableWidgetDefault.horizontalHeaderItem(1)
        item.setText(_translate("MainWindowImport", "Title"))
        item = self.tableWidgetDefault.horizontalHeaderItem(2)
        item.setText(_translate("MainWindowImport", "Stock"))
        item = self.tableWidgetDefault.horizontalHeaderItem(3)
        item.setText(_translate("MainWindowImport", "Price"))
        self.lineEditQuantity.setPlaceholderText(_translate("MainWindowImport", "*Quantity"))
        self.pushButtonAdd.setText(_translate("MainWindowImport", " Add"))
        self.label_7.setText(_translate("MainWindowImport", "Invoice ID"))
        self.labelGoodInvoiceID.setText(_translate("MainWindowImport", "#0000"))
        self.label_10.setText(_translate("MainWindowImport", "Order Creator"))
        self.labelAdminName.setText(_translate("MainWindowImport", "Admin"))
        self.label_9.setText(_translate("MainWindowImport", "Vendor"))
        item = self.tableWidgetImport.horizontalHeaderItem(0)
        item.setText(_translate("MainWindowImport", "Album ID"))
        item = self.tableWidgetImport.horizontalHeaderItem(1)
        item.setText(_translate("MainWindowImport", "Title"))
        item = self.tableWidgetImport.horizontalHeaderItem(2)
        item.setText(_translate("MainWindowImport", "Quantity"))
        item = self.tableWidgetImport.horizontalHeaderItem(3)
        item.setText(_translate("MainWindowImport", "Price"))
        self.pushButtonEdit.setText(_translate("MainWindowImport", "Edit Quantity"))
        self.pushButtonDelete.setText(_translate("MainWindowImport", "  Delete"))
        self.label_12.setText(_translate("MainWindowImport", "Total Price = "))
        self.labelTotalPrice.setText(_translate("MainWindowImport", "50000"))
        self.pushButtonImportEx.setText(_translate("MainWindowImport", "Export "))
