# Form implementation generated from reading ui file 'D:\code hk2\Final_KTLT\USER_INTERFACE\Invoice\MainWindowDetailInvoice.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_MainWindowAddAdmin(object):
    def setupUi(self, MainWindowAddAdmin):
        MainWindowAddAdmin.setObjectName("MainWindowAddAdmin")
        MainWindowAddAdmin.resize(889, 684)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindowAddAdmin)
        self.centralwidget.setObjectName("centralwidget")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 881, 651))
        self.label_8.setStyleSheet("background-color: rgb(242, 248, 255);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 881, 71))
        font = QtGui.QFont()
        font.setFamily("CocogooseProTrial Bold")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("  background-color: #0581F9;\n"
"font: 75 20pt \"CocogooseProTrial Bold\";\n"
"    padding: 5px;\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"")
        self.label.setObjectName("label")
        self.horizontalGroupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.horizontalGroupBox_3.setGeometry(QtCore.QRect(30, 550, 821, 80))
        self.horizontalGroupBox_3.setObjectName("horizontalGroupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_3)
        self.horizontalLayout_3.setContentsMargins(19, -1, 19, -1)
        self.horizontalLayout_3.setSpacing(9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_12 = QtWidgets.QLabel(parent=self.horizontalGroupBox_3)
        self.label_12.setStyleSheet("font: 63 14pt \"Montserrat SemiBold\";\n"
"color: rgb(229, 0, 0);")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.labelTotalPrice = QtWidgets.QLabel(parent=self.horizontalGroupBox_3)
        self.labelTotalPrice.setStyleSheet("font: 81 14pt \"Montserrat ExtraBold\";\n"
"color: rgb(229, 0, 0);")
        self.labelTotalPrice.setObjectName("labelTotalPrice")
        self.horizontalLayout_3.addWidget(self.labelTotalPrice)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButtonExcel = QtWidgets.QPushButton(parent=self.horizontalGroupBox_3)
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButtonExcel.setFont(font)
        self.pushButtonExcel.setStyleSheet("QPushButton {\n"
"    background-color: #FFFFFF; /* Màu nền mặc định */\n"
"    border-radius: 10px; \n"
"    border: 2px solid #79DADC;\n"
"    padding: 5px;\n"
"    color: #79DADC;\n"
"    font: 63 10pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #79DADC; /* Màu khi di chuột */  \n"
"    color: #FFFFFF;\n"
"    border: 2px solid #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FFFFFF; /* Màu khi nhấn */\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    background-color: #79DADC; /* Màu khi di chuột */  \n"
"    border:5px solid #B4EDEE;\n"
"    color: #FFFFFF;\n"
"\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\code hk2\\Final_KTLT\\USER_INTERFACE\\Invoice\\../../RESOURCE/ICON/exc.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonExcel.setIcon(icon)
        self.pushButtonExcel.setIconSize(QtCore.QSize(30, 50))
        self.pushButtonExcel.setObjectName("pushButtonExcel")
        self.horizontalLayout_3.addWidget(self.pushButtonExcel)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(45, 100, 281, 67))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setStyleSheet("color: rgb(14, 23, 67);\n"
"font: 57 10pt \"Montserrat Medium\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.labelInvoiceID = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.labelInvoiceID.setStyleSheet("color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";")
        self.labelInvoiceID.setText("")
        self.labelInvoiceID.setObjectName("labelInvoiceID")
        self.gridLayout.addWidget(self.labelInvoiceID, 0, 1, 1, 1)
        self.labelVendor = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.labelVendor.setStyleSheet("color: rgb(14, 23, 67);\n"
"font: 57 10pt \"Montserrat Medium\";")
        self.labelVendor.setObjectName("labelVendor")
        self.gridLayout.addWidget(self.labelVendor, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setStyleSheet("color: rgb(14, 23, 67);\n"
"font: 57 10pt \"Montserrat Medium\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(500, 100, 308, 67))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.label_4.setStyleSheet("color: rgb(14, 23, 67);\n"
"font: 57 10pt \"Montserrat Medium\";")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.labelTime = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.labelTime.setStyleSheet("color: rgb(14, 23, 67);\n"
"font: 57 10pt \"Montserrat Medium\";")
        self.labelTime.setObjectName("labelTime")
        self.gridLayout_2.addWidget(self.labelTime, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.label_5.setStyleSheet("color: rgb(14, 23, 67);\n"
"font: 57 10pt \"Montserrat Medium\";")
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.labelOrderCreator = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.labelOrderCreator.setStyleSheet("color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";")
        self.labelOrderCreator.setText("")
        self.labelOrderCreator.setObjectName("labelOrderCreator")
        self.gridLayout_2.addWidget(self.labelOrderCreator, 0, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 190, 821, 341))
        self.tableWidget.setToolTip("")
        self.tableWidget.setStyleSheet("padding: 5px;\n"
"border-radius: 10px;\n"
"color: rgb(14, 23, 67);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 57 10pt \"Montserrat Medium\";")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        MainWindowAddAdmin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindowAddAdmin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 889, 26))
        self.menubar.setObjectName("menubar")
        MainWindowAddAdmin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindowAddAdmin)
        self.statusbar.setObjectName("statusbar")
        MainWindowAddAdmin.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowAddAdmin)
        QtCore.QMetaObject.connectSlotsByName(MainWindowAddAdmin)

    def retranslateUi(self, MainWindowAddAdmin):
        _translate = QtCore.QCoreApplication.translate
        MainWindowAddAdmin.setWindowTitle(_translate("MainWindowAddAdmin", "Add new admin"))
        self.label.setText(_translate("MainWindowAddAdmin", "<html><head/><body><p align=\"center\">Invoice details</p></body></html>"))
        self.label_12.setText(_translate("MainWindowAddAdmin", "Total Price = "))
        self.labelTotalPrice.setText(_translate("MainWindowAddAdmin", "50000"))
        self.pushButtonExcel.setText(_translate("MainWindowAddAdmin", "EXPORT EXCEL"))
        self.label_3.setText(_translate("MainWindowAddAdmin", "Vendor:"))
        self.labelVendor.setText(_translate("MainWindowAddAdmin", "Vn30 (để cho có vd)"))
        self.label_2.setText(_translate("MainWindowAddAdmin", "Invoice_ID:"))
        self.label_4.setText(_translate("MainWindowAddAdmin", "Time:"))
        self.labelTime.setText(_translate("MainWindowAddAdmin", "Vn30 (để cho có vd)"))
        self.label_5.setText(_translate("MainWindowAddAdmin", "Order_Creator:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindowAddAdmin", "Number"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindowAddAdmin", "Invoice ID"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindowAddAdmin", "Vendor"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindowAddAdmin", "Order Ceator"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindowAddAdmin", "Time"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindowAddAdmin", "Total Sales"))
