# Form implementation generated from reading ui file 'D:\code hk2\Final_KTLT\USER_INTERFACE\Admin\MainWindowEditAmin.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindowAddAdmin(object):
    def setupUi(self, MainWindowAddAdmin):
        MainWindowAddAdmin.setObjectName("MainWindowAddAdmin")
        MainWindowAddAdmin.resize(809, 627)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindowAddAdmin)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 110, 698, 315))
        self.groupBox.setMaximumSize(QtCore.QSize(100000, 700))
        self.groupBox.setStyleSheet("padding: 5px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(77, 77, 77);\n"
"font: 25 12pt \"Montserrat Light\";")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 10, 661, 295))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_2.setStyleSheet("color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_3.setStyleSheet("color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_4.setStyleSheet("color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_5.setStyleSheet("color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_6.setStyleSheet("color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";")
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.lineEditStaffID = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEditStaffID.setStyleSheet("background-color: rgb(242, 248, 255);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";\n"
"padding: 10px;")
        self.lineEditStaffID.setFrame(False)
        self.lineEditStaffID.setObjectName("lineEditStaffID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditStaffID)
        self.lineEditName = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEditName.setStyleSheet("background-color: rgb(242, 248, 255);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";\n"
"padding: 10px;")
        self.lineEditName.setObjectName("lineEditName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditName)
        self.lineEditPosition = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEditPosition.setStyleSheet("background-color: rgb(242, 248, 255);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";\n"
"padding: 10px;")
        self.lineEditPosition.setObjectName("lineEditPosition")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditPosition)
        self.lineEditPhone = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEditPhone.setStyleSheet("background-color: rgb(242, 248, 255);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";\n"
"padding: 10px;")
        self.lineEditPhone.setObjectName("lineEditPhone")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditPhone)
        self.lineEditEmail = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEditEmail.setStyleSheet("background-color: rgb(242, 248, 255);\n"
"color: rgb(14, 23, 67);\n"
"font: 57 12pt \"Montserrat Medium\";\n"
"padding: 10px;")
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditEmail)
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 771, 531))
        self.label_8.setStyleSheet("background-color: rgb(242, 248, 255);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 771, 71))
        self.label.setStyleSheet("  background-color: #0581F9;\n"
"font: 75 24pt \"CocogooseProTrial Bold\";\n"
"    padding: 5px;\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"")
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 440, 691, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonSave = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButtonSave.setMaximumSize(QtCore.QSize(170, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButtonSave.setFont(font)
        self.pushButtonSave.setToolTipDuration(-1)
        self.pushButtonSave.setStyleSheet("QPushButton {\n"
"    background-color: #FF2090; /* Màu nền mặc định */\n"
"\n"
"    border-radius: 10px; \n"
"    padding: 5px;\n"
" \n"
"    font: 57 14pt \"Montserrat Medium\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFA2D1; /* Màu khi di chuột */  \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FF2090; /* Màu khi nhấn */\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 5px solid #FFA2D1; /* Viền khi nút được focus */ \n"
"}\n"
"\n"
"\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\code hk2\\Final_KTLT\\USER_INTERFACE\\Admin\\../../RESOURCE/ICON/1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSave.setIcon(icon)
        self.pushButtonSave.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayout.addWidget(self.pushButtonSave)
        self.pushButtonCancel = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButtonCancel.setMaximumSize(QtCore.QSize(170, 50))
        self.pushButtonCancel.setStyleSheet("QPushButton {\n"
"    background-color: #35B6E8; /* Màu nền mặc định */\n"
"\n"
"    border-radius: 10px; \n"
"    padding: 5px;\n"
" \n"
"    font: 57 14pt \"Montserrat Medium\";\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A3E3FC; /* Màu khi di chuột */  \n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #35B6E8; /* Màu khi nhấn */\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 5px solid #A3E3FC; /* Viền khi nút được focus */ \n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\code hk2\\Final_KTLT\\USER_INTERFACE\\Admin\\../../RESOURCE/ICON/cancel.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonCancel.setIcon(icon1)
        self.pushButtonCancel.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.label_8.raise_()
        self.groupBox.raise_()
        self.label.raise_()
        self.horizontalLayoutWidget.raise_()
        MainWindowAddAdmin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindowAddAdmin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 809, 26))
        self.menubar.setObjectName("menubar")
        MainWindowAddAdmin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindowAddAdmin)
        self.statusbar.setObjectName("statusbar")
        MainWindowAddAdmin.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowAddAdmin)
        QtCore.QMetaObject.connectSlotsByName(MainWindowAddAdmin)

    def retranslateUi(self, MainWindowAddAdmin):
        _translate = QtCore.QCoreApplication.translate
        MainWindowAddAdmin.setWindowTitle(_translate("MainWindowAddAdmin", "Add new admin"))
        self.label_2.setText(_translate("MainWindowAddAdmin", "Staff_id:"))
        self.label_3.setText(_translate("MainWindowAddAdmin", "Name:"))
        self.label_4.setText(_translate("MainWindowAddAdmin", "Position:"))
        self.label_5.setText(_translate("MainWindowAddAdmin", "Phone:"))
        self.label_6.setText(_translate("MainWindowAddAdmin", "Email:"))
        self.label.setText(_translate("MainWindowAddAdmin", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Edit admin\'s information</span></p></body></html>"))
        self.pushButtonSave.setToolTip(_translate("MainWindowAddAdmin", "<html><head/><body><p><span style=\" font-size:12pt; color:#ff2090;\">New</span></p></body></html>"))
        self.pushButtonSave.setText(_translate("MainWindowAddAdmin", " Save"))
        self.pushButtonCancel.setToolTip(_translate("MainWindowAddAdmin", "<html><head/><body><p><span style=\" font-size:12pt; color:#35b6e8;\">Edit</span></p></body></html>"))
        self.pushButtonCancel.setText(_translate("MainWindowAddAdmin", " Cancel"))
